<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="7" failures="0" skipped="1" tests="8" time="0.238" timestamp="2025-05-14T04:41:26.099677" hostname="d5d1c67e5751"><testcase classname="" name="tests.integration.communication.test_a2a_interoperability" time="0.000"><skipped message="collection skipped">('/workspaces/template-python-dev/tests/integration/communication/test_a2a_interoperability.py', 23, 'Skipped: Skipping A2A interoperability tests due to missing libraries: crewai, langgraph')</skipped></testcase><testcase classname="" name="tests.integration.communication.test_a2a_orchestration_flow" time="0.000"><error message="collection failure">ImportError while importing test module '/workspaces/template-python-dev/tests/integration/communication/test_a2a_orchestration_flow.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/communication/test_a2a_orchestration_flow.py:35: in &lt;module&gt;
    from ailf.communication.a2a_server import AILFASA2AServer, A2AAgentExecutor, A2ARequestContext, A2ATaskManager
E   ImportError: cannot import name 'A2ATaskManager' from 'ailf.communication.a2a_server' (/workspaces/template-python-dev/ailf/communication/a2a_server.py)</error></testcase><testcase classname="" name="tests.integration.test_ailf_redis" time="0.000"><error message="collection failure">ImportError while importing test module '/workspaces/template-python-dev/tests/integration/test_ailf_redis.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/test_ailf_redis.py:17: in &lt;module&gt;
    from ailf.messaging.redis import RedisClient, RedisStream, RedisPubSub
E   ModuleNotFoundError: No module named 'ailf.messaging.redis'</error></testcase><testcase classname="" name="tests.integration.utils.test_ai_engine_functions_int" time="0.000"><error message="collection failure">ImportError while importing test module '/workspaces/template-python-dev/tests/integration/utils/test_ai_engine_functions_int.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/utils/test_ai_engine_functions_int.py:6: in &lt;module&gt;
    from utils.ai_engine import AIEngine
utils/__init__.py:6: in &lt;module&gt;
    from .storage import local
utils/storage/__init__.py:3: in &lt;module&gt;
    from . import setup
utils/storage/setup.py:51: in &lt;module&gt;
    from ..cloud.secrets import secret_manager
utils/cloud/__init__.py:3: in &lt;module&gt;
    from . import secrets
utils/cloud/secrets.py:16: in &lt;module&gt;
    from .logging import setup_logging
E   ModuleNotFoundError: No module named 'utils.cloud.logging'</error></testcase><testcase classname="" name="tests.integration.utils.test_ai_engine_int" time="0.000"><error message="collection failure">ImportError while importing test module '/workspaces/template-python-dev/tests/integration/utils/test_ai_engine_int.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/utils/test_ai_engine_int.py:6: in &lt;module&gt;
    from utils.ai_engine import AIEngine
utils/__init__.py:6: in &lt;module&gt;
    from .storage import local
utils/storage/__init__.py:3: in &lt;module&gt;
    from . import setup
utils/storage/setup.py:51: in &lt;module&gt;
    from ..cloud.secrets import secret_manager
utils/cloud/__init__.py:3: in &lt;module&gt;
    from . import secrets
utils/cloud/secrets.py:16: in &lt;module&gt;
    from .logging import setup_logging
E   ModuleNotFoundError: No module named 'utils.cloud.logging'</error></testcase><testcase classname="" name="tests.integration.utils.test_int_ai_engine" time="0.000"><error message="collection failure">ImportError while importing test module '/workspaces/template-python-dev/tests/integration/utils/test_int_ai_engine.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/utils/test_int_ai_engine.py:9: in &lt;module&gt;
    from ailf.ai_engine import AIEngine
E   ModuleNotFoundError: No module named 'ailf.ai_engine'</error></testcase><testcase classname="" name="tests.integration.utils.test_int_redis" time="0.000"><error message="collection failure">ImportError while importing test module '/workspaces/template-python-dev/tests/integration/utils/test_int_redis.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/utils/test_int_redis.py:22: in &lt;module&gt;
    from src.ailf.messaging.redis import (
src/ailf/__init__.py:11: in &lt;module&gt;
    from .async_tasks import TaskManager, TaskStatus
src/ailf/async_tasks.py:52: in &lt;module&gt;
    from ailf.core.logging import setup_logging
E   ModuleNotFoundError: No module named 'ailf.core'</error></testcase><testcase classname="" name="tests.integration.utils.test_zmq_devices_int" time="0.000"><error message="collection failure">ImportError while importing test module '/workspaces/template-python-dev/tests/integration/utils/test_zmq_devices_int.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/utils/test_zmq_devices_int.py:7: in &lt;module&gt;
    from utils.zmq_devices import ZmqDevice
utils/__init__.py:6: in &lt;module&gt;
    from .storage import local
utils/storage/__init__.py:3: in &lt;module&gt;
    from . import setup
utils/storage/setup.py:51: in &lt;module&gt;
    from ..cloud.secrets import secret_manager
utils/cloud/__init__.py:3: in &lt;module&gt;
    from . import secrets
utils/cloud/secrets.py:16: in &lt;module&gt;
    from .logging import setup_logging
E   ModuleNotFoundError: No module named 'utils.cloud.logging'</error></testcase></testsuite></testsuites>